import type { Choice, LegacyStage, QuizQuestion } from '../types'

export const AGENT_SOURCE_URL =
  'https://gcnum0i2ctpz.feishu.cn/docx/T5yudp4hMo6iMwxbYV0cftiIn6a'

export const acts = [
  { id: 1, title: '看见 Agent' },
  { id: 2, title: '让它行动' },
  { id: 3, title: '让它可靠' },
  { id: 4, title: '让系统变强' },
  { id: 5, title: '做出你的助手' },
]

type QuizSeed = {
  prompt: string
  choices: [string, string, string]
  answer: 0 | 1 | 2
  explanation: string
  critical?: boolean
}

const predictionChoices = (a: string, b: string, c: string): Choice[] => [
  { id: 'a', label: a },
  { id: 'b', label: b },
  { id: 'c', label: c },
]

const makeQuiz = (stageId: number, scenarios: QuizSeed[], knowledge: QuizSeed[]): QuizQuestion[] =>
  [...scenarios.map((seed) => ({ ...seed, scenario: true })), ...knowledge.map((seed) => ({ ...seed, scenario: false }))].map(
    (seed, index) => ({
      id: `${stageId}-${index + 1}`,
      prompt: seed.prompt,
      choices: seed.choices.map((label, choiceIndex) => ({
        id: ['a', 'b', 'c'][choiceIndex],
        label,
      })),
      answer: ['a', 'b', 'c'][seed.answer],
      explanation: seed.explanation,
      scenario: seed.scenario,
      critical: seed.critical,
    }),
  )

export const stages: LegacyStage[] = [
  {
    id: 1,
    act: 1,
    title: '它为什么不只是聊天',
    duration: 12,
    sourceRange: '原文 1.1–1.2',
    problem: '一个客服机器人能解释退款规则，却不会查订单、创建退款单，也不知道任务有没有完成。它算 Agent 吗？',
    outcome: '学完后，你能在一分钟内判断一个 AI 产品是真正的 Agent，还是只是套了界面的聊天模型。',
    prediction: {
      prompt: '让这个机器人真正完成退款，最关键的新增能力是什么？',
      choices: predictionChoices('回答得更长', '能调用订单与退款工具', '换一个更大的模型'),
      answer: 'b',
      feedback: '关键不是“更会说”，而是能观察状态、决定下一步、调用工具并核对结果。',
    },
    formula: 'Agent = 模型 + 规划 + 记忆 + 工具 + 反馈闭环',
    lesson: [
      {
        title: '聊天给建议，Agent 交付结果',
        paragraphs: [
          '语言模型擅长理解与生成文字，但文字本身不会改变外部世界。Agent 在模型外面加上一套执行循环：先理解目标，再决定动作，调用工具，观察结果，直到完成或安全停止。',
          '因此，判断 Agent 时不要看宣传语，要看它能否持续推进一个目标，并对执行结果负责。',
        ],
      },
      {
        title: '三种必须出现的自主性',
        paragraphs: ['真正有用的 Agent 同时具备感知、决策和执行。缺少任何一项，都会退化成问答器或固定流程。'],
        points: ['感知：读懂任务与当前环境', '决策：选择下一步并在变化时调整', '执行：调用真实工具并检查结果'],
      },
      {
        title: '边界比聪明更重要',
        paragraphs: [
          '自主不等于无限权限。可靠的 Agent 会在付款、删除、对外发送等高风险动作前请求确认，并在信息不足时主动澄清。',
        ],
      },
    ],
    practice: {
      title: '拆解一个“自动回复”产品',
      brief: '任选一个你见过的 AI 客服，写出它能感知什么、能决定什么、能执行什么。',
      success: '能指出至少一个“它只是回答，没有真正行动”的证据。',
    },
    bridge: '会判断 Agent 之后，下一个问题是：这些能力在系统里分别放在哪里？',
    quiz: makeQuiz(
      1,
      [
        { prompt: '用户说“帮我把明天下午的会议改到周五”，哪个行为最像 Agent？', choices: ['给出改期建议', '读取日历、检查冲突、修改后回报', '解释如何手动改期'], answer: 1, explanation: 'Agent 需要实际读取与改变日历状态。', critical: true },
        { prompt: '一个写作工具生成了三版标题，但不会保存到内容系统。应如何判断？', choices: ['它一定是 Agent', '它是生成模型能力，未形成执行闭环', '只要用了大模型就是 Agent'], answer: 1, explanation: '生成内容不等于自主执行外部任务。' },
        { prompt: '退款 Agent 查到订单已过期，最可靠的下一步是什么？', choices: ['编造一个退款编号', '说明限制并转入人工或例外流程', '不断重复调用退款接口'], answer: 1, explanation: '遇到边界条件要安全停止或升级处理。' },
        { prompt: '运营 Agent 准备向 10 万用户发消息，应该怎样设计？', choices: ['直接发送以体现自主性', '先生成预览并请求确认', '关闭日志减少干扰'], answer: 1, explanation: '高影响外部动作需要人类确认。' },
        { prompt: '数据助手先查表，再发现字段缺失并追问用户。这体现了什么？', choices: ['感知与动态决策', '只是在背模板', '模型参数更大'], answer: 0, explanation: '它根据环境反馈改变了下一步动作。' },
      ],
      [
        { prompt: 'Agent 与普通聊天模型最本质的差异是什么？', choices: ['界面更复杂', '能围绕目标执行并验证动作', '回答字数更多'], answer: 1, explanation: '执行闭环是核心差异。' },
        { prompt: '下面哪组最接近 Agent 的核心组成？', choices: ['模型、工具、记忆、规划', '网页、按钮、头像、动画', '数据集、显卡、显示器、键盘'], answer: 0, explanation: '模型负责推理，其他模块让推理能持续并作用于环境。' },
        { prompt: '“自主”在可靠 Agent 中意味着什么？', choices: ['拥有所有权限', '在明确边界内自行推进', '永远不向用户提问'], answer: 1, explanation: '自主必须受权限、风险和停止条件约束。' },
      ],
    ),
  },
  {
    id: 2,
    act: 1,
    title: '四层架构与一次数据流',
    duration: 15,
    sourceRange: '原文 2.1–2.3',
    problem: '同一个客服 Agent 时而忘记用户要求，时而重复查订单。问题到底出在模型、记忆、工具，还是流程控制？',
    outcome: '你会用“交互—控制—能力—数据”四层图定位问题，而不是笼统地说“AI 不够聪明”。',
    prediction: {
      prompt: '订单接口已经正确返回，但 Agent 仍重复查询。优先检查哪一层？',
      choices: predictionChoices('控制层的状态与停止条件', '交互层的字体', '换数据库品牌'),
      answer: 'a',
      feedback: '工具返回正常却重复动作，通常是控制层没有记录结果或判断完成。',
    },
    formula: '输入 → 控制层编排 → 模型决策 → 工具执行 → 状态写回 → 继续或停止',
    lesson: [
      { title: '四层各管一件事', paragraphs: ['交互层接收目标并呈现结果；控制层维护循环、状态和权限；能力层放模型与工具；数据层保存知识、记忆和业务数据。'], points: ['交互层：人怎样提出任务', '控制层：下一步做什么', '能力层：靠什么完成动作', '数据层：事实和历史放哪里'] },
      { title: '跟着一次请求走', paragraphs: ['用户提出目标后，控制层把上下文交给模型。模型产生结构化动作，工具执行后把结果写回状态。控制层再次判断：继续、重试、追问、转人工，还是完成。'] },
      { title: '用层次定位故障', paragraphs: ['看不懂用户多半在交互或意图环节；选错动作多半在提示与规划；接口报错属于工具；重复循环属于状态或停止条件；忘记历史属于记忆。'] },
    ],
    practice: { title: '画出订单查询链路', brief: '用六个箭头画出“用户问物流进度”从输入到最终回答的数据流。', success: '每一步都能标出属于哪一层，并写出一次可能失败的地方。' },
    bridge: '架构图解释了能力放在哪里。下一关开始拆开 Agent 的“大脑”：模型到底负责什么？',
    quiz: makeQuiz(
      2,
      [
        { prompt: '用户输入正常，但界面没有展示工具执行结果。先查哪一层？', choices: ['交互层的数据绑定', '模型参数量', '向量维度'], answer: 0, explanation: '结果已产生但未显示，优先检查交互层。', critical: true },
        { prompt: 'Agent 把“退款”动作调用成“查物流”。最可能的责任点是？', choices: ['动作选择与工具描述', '数据库备份', '按钮圆角'], answer: 0, explanation: '工具选择依赖控制提示、规划与工具描述。' },
        { prompt: '工具返回“订单不存在”，系统仍连续调用十次。先补什么？', choices: ['更长的欢迎语', '状态记录与停止分支', '更多图标'], answer: 1, explanation: '控制层必须根据结果改变流程。' },
        { prompt: '跨会话后 Agent 忘了客户偏好，问题主要在哪层？', choices: ['数据层的长期记忆', '交互层颜色', '网络域名'], answer: 0, explanation: '跨会话信息需要持久化记忆。' },
        { prompt: '业务规则更新了，Agent 仍引用旧规则。最先检查？', choices: ['知识数据更新与检索', '模型温度', '页面宽度'], answer: 0, explanation: '事实过期首先是数据与检索问题。' },
      ],
      [
        { prompt: '谁负责维护执行循环和停止条件？', choices: ['控制层', '能力层', '交互层'], answer: 0, explanation: '控制层编排整个过程。' },
        { prompt: '工具执行结果下一步应该去哪？', choices: ['丢弃', '写回状态供下一轮判断', '只展示给开发者'], answer: 1, explanation: '观察结果是闭环成立的必要条件。' },
        { prompt: '数据库和长期记忆更接近哪一层？', choices: ['数据层', '交互层', '展示层'], answer: 0, explanation: '它们负责保存可复用的事实与历史。' },
      ],
    ),
  },
  {
    id: 3,
    act: 2,
    title: '模型是大脑，不是整个身体',
    duration: 14,
    sourceRange: '原文 3.1–3.2',
    problem: '换了更贵的模型后，Agent 仍会编造库存。继续升级模型，还是改变系统设计？',
    outcome: '你会区分“模型推理问题”和“事实、权限、执行问题”，知道什么时候不该靠换模型解决。',
    prediction: { prompt: '要回答实时库存，最可靠的做法是什么？', choices: predictionChoices('要求模型认真回忆', '调用库存接口并引用结果', '把温度调高'), answer: 'b', feedback: '实时事实不在模型参数里，应通过工具获取并让回答绑定工具结果。' },
    formula: '模型负责理解与选择；外部事实来自检索或工具',
    lesson: [
      { title: '模型擅长的三件事', paragraphs: ['模型擅长把自然语言转成目标、根据上下文推理下一步、把结构化结果组织成可读回答。它是决策引擎，不是事实数据库，也不是权限系统。'] },
      { title: '结构化输出是接口', paragraphs: ['让模型输出 JSON 等稳定结构，控制层才能可靠读取动作名和参数。自然语言适合给人看，结构化数据适合给程序执行。'], points: ['动作名必须在允许列表内', '参数要符合 schema', '不确定时输出澄清动作'] },
      { title: '为不同任务选模型', paragraphs: ['复杂规划需要更强推理；固定分类可用更快更便宜的模型；高风险动作还需要规则校验。模型选择是成本、速度、准确率的平衡。'] },
    ],
    codeLens: { title: '只读懂这段接口', code: `type Action = {\n  tool: 'inventory_lookup' | 'ask_user'\n  input: { sku?: string }\n  reason: string\n}`, watch: ['tool 只能从允许列表选择', 'input 是工具真正收到的参数', 'reason 供日志与调试使用'] },
    practice: { title: '给模型划边界', brief: '把“回答商品库存”拆成模型负责、工具负责、规则负责三列。', success: '实时数量不由模型猜；无商品编号时会先追问。' },
    bridge: '模型能选下一步，但复杂目标往往有很多步。下一关解决“先做什么、后做什么”。',
    quiz: makeQuiz(
      3,
      [
        { prompt: '商品库存每分钟变化，Agent 应怎样回答？', choices: ['调用库存接口', '依赖模型记忆', '随机给一个范围'], answer: 0, explanation: '实时事实必须来自实时数据源。', critical: true },
        { prompt: '模型输出工具名时偶尔拼错，最佳改进是？', choices: ['允许自由文本', '使用枚举 schema 校验', '增大字号'], answer: 1, explanation: '结构化约束能阻止非法动作名。' },
        { prompt: '每天要分 5 万条客服意图，任务简单稳定。如何选模型？', choices: ['一律最贵模型', '用小模型并以评测验证', '完全不测'], answer: 1, explanation: '按任务难度和评测结果选择模型。' },
        { prompt: '付款动作即将执行，模型说“我很确定”。系统还需要什么？', choices: ['权限与金额规则校验', '更有感染力的文案', '关闭日志'], answer: 0, explanation: '模型置信不能代替业务权限。' },
        { prompt: '用户只说“查一下”，缺少对象。模型应输出什么？', choices: ['编造对象', 'ask_user 澄清动作', '直接结束且不说明'], answer: 1, explanation: '信息不足应显式澄清。' },
      ],
      [
        { prompt: '自然语言和结构化输出的分工是什么？', choices: ['都只给人看', '前者给人，后者便于程序执行', '后者更适合写诗'], answer: 1, explanation: '稳定结构是控制层与模型的接口。' },
        { prompt: '模型参数中最不适合保存哪类信息？', choices: ['语言模式', '实时库存', '常见表达'], answer: 1, explanation: '实时数据变化快，应从外部读取。' },
        { prompt: '模型在 Agent 中的核心角色更接近？', choices: ['决策引擎', '数据库备份', '权限管理员'], answer: 0, explanation: '模型理解目标并选择动作。' },
      ],
    ),
  },
  {
    id: 4,
    act: 2,
    title: '把目标拆成能执行的计划',
    duration: 16,
    sourceRange: '原文 3.3',
    problem: '“分析本月销售下滑原因”听起来只有一句话，但执行时需要取数、清洗、对比、查资料、验证。怎样避免一上来就乱调用工具？',
    outcome: '你会写出可检查、可调整的执行计划，并知道什么时候应重新规划。',
    prediction: { prompt: '第一步最应该做什么？', choices: predictionChoices('立刻写结论', '确认指标口径与数据范围', '搜索一句行业新闻就结束'), answer: 'b', feedback: '目标和口径不清时，越早执行越容易把错误放大。' },
    formula: '目标 → 子任务 → 前置条件 → 动作 → 验证 → 必要时重规划',
    lesson: [
      { title: '好计划能被检查', paragraphs: ['“分析一下”不是计划。每个步骤都要有输入、动作和可观察结果，例如“读取 7 月订单表，确认行数与缺失率”。'] },
      { title: '静态计划与动态计划', paragraphs: ['简单固定任务可先列完整步骤；环境变化大的任务适合每完成一步再决定下一步。ReAct 就属于边执行边调整。'] },
      { title: '把验证写进计划', paragraphs: ['不要把验证留到最后。取数后查范围，计算后交叉校验，写结论前确认数据是否支持。验证步骤能阻断错误传播。'] },
    ],
    practice: { title: '拆解一次销售分析', brief: '把“找出销售下降原因”拆成 5 个带输入和检查结果的步骤。', success: '至少包含口径确认、数据质量检查和结论验证。' },
    bridge: '计划跨越多轮以后，Agent 必须记得已经做过什么。下一关进入记忆。',
    quiz: makeQuiz(
      4,
      [
        { prompt: '用户让 Agent 比较两份报表，但时间范围不同。先做什么？', choices: ['直接比较', '确认并统一口径', '只看总额'], answer: 1, explanation: '前置条件不一致时结果没有可比性。', critical: true },
        { prompt: '第三步发现数据缺失 40%，计划应怎样变化？', choices: ['忽略并继续', '暂停结论，补数或说明限制', '编造缺失值'], answer: 1, explanation: '环境反馈要求动态重规划。' },
        { prompt: '自动发布文章的计划中，哪一步最该放在发布前？', choices: ['事实核验与预览确认', '再换一次字体', '删除来源'], answer: 0, explanation: '高影响动作前需要验证与确认。' },
        { prompt: '一个步骤写“处理数据”。怎样改得可执行？', choices: ['保持抽象', '写明输入、清洗规则和检查结果', '改成“认真处理”'], answer: 1, explanation: '可执行步骤必须可观察和验收。' },
        { prompt: '外部 API 返回限流，计划的合理调整是？', choices: ['无限立即重试', '退避后重试或切换备用源', '假装成功'], answer: 1, explanation: '计划要能根据环境约束调整。' },
      ],
      [
        { prompt: '计划中最容易被忽略但最重要的部分是？', choices: ['验证步骤', '标题颜色', '欢迎语'], answer: 0, explanation: '验证阻止错误沿链路扩散。' },
        { prompt: '动态规划适合什么任务？', choices: ['环境反馈会改变后续动作', '每次完全固定', '没有任何工具'], answer: 0, explanation: '动态任务应边执行边更新计划。' },
        { prompt: '一个好子任务至少应包含？', choices: ['输入、动作、可观察结果', '一句口号', '多个形容词'], answer: 0, explanation: '这三项让步骤可执行、可检查。' },
      ],
    ),
  },
  {
    id: 5,
    act: 2,
    title: '短期记忆与长期记忆',
    duration: 15,
    sourceRange: '原文 3.4',
    problem: '用户上一轮说预算 3000 元，Agent 下一轮推荐了 5000 元方案；第二天又完全忘记用户偏好。两种“忘记”是同一个问题吗？',
    outcome: '你会区分工作记忆、长期记忆和知识检索，避免把所有历史都塞进提示词。',
    prediction: { prompt: '预算属于本次任务正在使用的信息，先放在哪里？', choices: predictionChoices('短期状态/工作记忆', '模型参数', '公开知识库'), answer: 'a', feedback: '本次任务的目标、约束与中间结果属于工作记忆；跨会话偏好才考虑长期记忆。' },
    formula: '短期记忆保任务状态；长期记忆保稳定偏好；知识库保存可引用事实',
    lesson: [
      { title: '三类信息不要混放', paragraphs: ['工作记忆服务当前任务，通常随任务结束而归档；长期记忆保存经过确认的稳定偏好；知识库保存文档与业务事实，可检索并引用来源。'] },
      { title: '写入比读取更难', paragraphs: ['不是用户说过的每句话都值得长期保存。写入前应判断是否稳定、有用、允许保存，并允许用户查看和删除。'] },
      { title: '摘要与检索控制上下文', paragraphs: ['对话很长时，保留当前目标、关键约束、已完成步骤与待办；旧细节转成摘要，需要时再检索，而不是无上限拼接。'] },
    ],
    practice: { title: '给信息分仓', brief: '把“本次预算、用户长期偏好、退款规则、刚查到的订单状态”放入正确记忆类型。', success: '能解释每条信息何时写入、何时过期。' },
    codexTask: { title: '做一个最小任务状态器', context: '学习项目需要保存当前目标、约束和已完成步骤。', goal: '实现可读写且可清空的本地任务状态。', scope: ['只处理单个任务', '使用 TypeScript 类型', '提供序列化与恢复'], constraints: ['不保存 API Key', '字段必须有明确含义', '坏数据回退到默认状态'], acceptance: ['刷新后状态仍在', '任务结束可清空', '损坏数据不会让应用崩溃'], tests: ['默认状态测试', '序列化往返测试', '坏 JSON 回退测试'] },
    bridge: '有了状态，Agent 还需要真正改变外部世界。下一关学习工具和 ReAct 循环。',
    quiz: makeQuiz(
      5,
      [
        { prompt: '用户本次任务要求“不要超过 3 次 API 调用”。这应保存在哪里？', choices: ['当前任务状态', '永久个人档案', '公开知识库'], answer: 0, explanation: '它是本次执行约束。', critical: true },
        { prompt: '用户明确说“以后都用中文回答”，最适合？', choices: ['长期偏好', '一次性工具结果', '模型权重'], answer: 0, explanation: '这是稳定且经用户确认的跨会话偏好。' },
        { prompt: '公司退款政策应放在哪里？', choices: ['可检索知识库', '用户私有偏好', '临时按钮状态'], answer: 0, explanation: '业务事实需要版本和来源。' },
        { prompt: '一段 200 轮对话快超出上下文。优先做什么？', choices: ['全部重复拼接', '摘要关键状态并按需检索', '随机删一半'], answer: 1, explanation: '摘要与检索能保留任务结构。' },
        { prompt: '用户随口说“今天有点累”，系统是否应永久记住？', choices: ['一定永久保存', '默认不保存，除非有明确用途与同意', '发给所有工具'], answer: 1, explanation: '长期记忆需要必要性和用户控制。' },
      ],
      [
        { prompt: '工作记忆最主要服务于？', choices: ['当前任务推进', '模型训练', '页面配色'], answer: 0, explanation: '它记录当前目标、约束和中间结果。' },
        { prompt: '长期记忆写入前最应考虑？', choices: ['是否稳定、有用、获准', '文字是否够长', '是否有 emoji'], answer: 0, explanation: '长期保存涉及价值、隐私与可控性。' },
        { prompt: '知识库与长期偏好的主要差异是？', choices: ['前者是可引用业务事实，后者是用户稳定偏好', '没有差异', '前者只能放图片'], answer: 0, explanation: '二者来源、权限和更新方式不同。' },
      ],
    ),
  },
  {
    id: 6,
    act: 2,
    title: '工具调用与 ReAct 循环',
    duration: 18,
    sourceRange: '原文 3.5、4.1–4.3',
    problem: 'Agent 需要先查销售数据，再算增长率，最后解释原因。怎样让它既会思考，又不会只思考不行动？',
    outcome: '你会读懂 Thought—Action—Observation 循环，并能写出清晰的工具说明与输入输出。',
    prediction: { prompt: '工具返回销售额为空后，下一步应该是什么？', choices: predictionChoices('继续计算并给结论', '观察为空的原因并决定补查或追问', '重复原答案'), answer: 'b', feedback: 'ReAct 的价值是让观察改变下一步，而不是机械执行预先想好的动作。' },
    formula: '思考 → 动作 → 观察 → 更新状态 → 再思考',
    lesson: [
      { title: '工具是受约束的能力接口', paragraphs: ['工具描述要说明何时用、需要哪些参数、返回什么、会产生什么副作用。模型不是直接操作世界，而是提出工具调用，由控制层校验后执行。'] },
      { title: 'ReAct 把推理接到现实', paragraphs: ['每轮模型根据目标和当前观察选择一个动作。工具结果回到上下文后，模型重新判断。这样计划能适应真实数据，而不是在执行前幻想所有结果。'] },
      { title: '观察必须可读且有限', paragraphs: ['工具错误要结构化，长结果要截断或摘要，敏感字段要隐藏。否则上下文会被日志淹没，模型也难以判断。'] },
    ],
    codeLens: { title: '工具签名就是合同', code: `type ToolResult<T> =\n  | { ok: true; data: T }\n  | { ok: false; error: string; retryable: boolean }\n\nasync function runTool(name: ToolName, input: ToolInput)`, watch: ['成功与失败是两条明确分支', 'retryable 告诉控制层能否重试', '输入类型限制模型能传什么'] },
    practice: { title: '设计“查订单”工具', brief: '写出工具名、用途、输入字段、成功返回、失败返回和副作用。', success: '模型能仅凭说明判断何时调用，且缺订单号时不会乱猜。' },
    codexTask: { title: '实现一个 Mock 工具循环', context: '先不用真实 API，模拟订单查询和退款资格判断。', goal: '实现最多 4 轮的 ReAct 状态机。', scope: ['两个 mock 工具', '结构化结果', '每轮写日志'], constraints: ['禁止真实退款', '每轮只调用一个工具', '达到终态立即停止'], acceptance: ['正常订单得到明确结论', '缺订单号会追问', '工具失败不会死循环'], tests: ['成功路径', '缺参路径', '可重试错误', '超过轮数停止'] },
    bridge: '循环能让 Agent 动起来，也带来最危险的问题：它可能停不下来。',
    quiz: makeQuiz(
      6,
      [
        { prompt: '搜索工具返回 429 限流，观察结果应包含什么？', choices: ['只写“失败”', '错误类型与是否可重试', '假装有结果'], answer: 1, explanation: '控制层需要结构化信息决定退避或停止。', critical: true },
        { prompt: '模型想调用不存在的 tool 名。控制层应？', choices: ['照样执行', '拒绝并返回允许列表错误', '映射到任意工具'], answer: 1, explanation: '动作必须经过白名单和 schema 校验。' },
        { prompt: '查订单工具需要 order_id，但用户没给。合理动作是？', choices: ['ask_user', '编造 ID', '连续调用空参数'], answer: 0, explanation: '缺参应进入澄清动作。' },
        { prompt: '工具结果有 10 万行。直接塞回上下文吗？', choices: ['全部塞入', '聚合、截断并保留可追溯引用', '随机取一行'], answer: 1, explanation: '观察要足够决策但不能淹没上下文。' },
        { prompt: '执行发邮件工具前，控制层最该检查？', choices: ['收件人、权限与确认状态', '模型文风', '屏幕分辨率'], answer: 0, explanation: '有副作用的工具必须做权限和参数校验。' },
      ],
      [
        { prompt: 'ReAct 中 Observation 的作用是？', choices: ['改变下一轮决策', '只用于装饰日志', '替代用户目标'], answer: 0, explanation: '观察让推理与真实环境闭环。' },
        { prompt: '工具描述至少要说明？', choices: ['用途、参数、返回与副作用', '品牌故事', '开发者头像'], answer: 0, explanation: '这些信息决定模型能否安全选用工具。' },
        { prompt: '谁最终执行模型提出的工具调用？', choices: ['受控的工具执行层', '模型参数本身', '用户浏览器历史'], answer: 0, explanation: '控制层校验后才交给工具执行。' },
      ],
    ),
  },
  {
    id: 7,
    act: 3,
    title: '停止条件、上下文与错误恢复',
    duration: 18,
    sourceRange: '原文 5.1、5.3–5.4',
    problem: 'Agent 一直在“搜索—总结—再搜索”，花了十分钟仍没有交付；偶发接口错误后还会从头重做。怎样让它可控？',
    outcome: '你会设计预算、终态、超时、重试与断点，让 Agent 失败得清楚、恢复得经济。',
    prediction: { prompt: '防止无限循环，最有效的组合是什么？', choices: predictionChoices('提示它“请不要循环”', '轮数/时间预算 + 明确终态 + 重复检测', '把温度调高'), answer: 'b', feedback: '可靠停止不能只靠模型自觉，要由控制层的硬约束兜底。' },
    formula: '停止 = 已完成 ∨ 需澄清 ∨ 风险升级 ∨ 预算耗尽 ∨ 不可恢复错误',
    lesson: [
      { title: '终态要提前定义', paragraphs: ['“模型说完成了”不够。系统要用可检查条件判断，例如文件已生成、必填字段齐全、结果通过验证。'] },
      { title: '重试不是重新来过', paragraphs: ['只对临时错误重试，采用退避和次数上限；保留已完成步骤，避免接口抖动让整个任务从头开始。'] },
      { title: '上下文只保留决策所需', paragraphs: ['维护结构化状态：目标、约束、已完成、最新观察、待办。原始长日志存外部，按需引用。'] },
    ],
    practice: { title: '给搜索 Agent 装刹车', brief: '写出 5 种停止条件，以及每种停止时要向用户说明什么。', success: '包含完成、缺信息、高风险、预算耗尽和不可恢复错误。' },
    bridge: '会停止还不够。下一关处理另一类常见故障：选错工具、参数错、结果不可信。',
    quiz: makeQuiz(
      7,
      [
        { prompt: 'Agent 连续三次得到同一搜索结果。应怎样处理？', choices: ['无限继续', '触发重复检测并换策略或停止', '隐藏日志'], answer: 1, explanation: '重复观察是循环信号。', critical: true },
        { prompt: '接口 503 暂时不可用，合理策略是？', choices: ['指数退避并限制次数', '每毫秒重试', '当作成功'], answer: 0, explanation: '临时错误适合有限退避重试。' },
        { prompt: '已经完成前 4 步，第 5 步失败。恢复时应？', choices: ['利用检查点从第 5 步继续', '全部重做', '删除状态'], answer: 0, explanation: '断点恢复减少成本和副作用。' },
        { prompt: '生成报告的“完成”如何验收？', choices: ['模型说完成', '文件存在且必需章节与数据校验通过', '运行时间超过一分钟'], answer: 1, explanation: '终态应由可观察条件判定。' },
        { prompt: '上下文快溢出时保留什么？', choices: ['所有原始日志', '目标、约束、关键观察和待办', '随机最后一句'], answer: 1, explanation: '保留影响下一步决策的信息。' },
      ],
      [
        { prompt: '硬停止条件主要由谁执行？', choices: ['控制层', '用户记忆', '页面样式'], answer: 0, explanation: '控制层负责轮数、时间和预算边界。' },
        { prompt: '哪些错误适合重试？', choices: ['明确的临时故障', '权限拒绝', '参数永远缺失'], answer: 0, explanation: '只有可能自行恢复的错误值得重试。' },
        { prompt: '检查点的价值是？', choices: ['从最近有效状态恢复', '让日志更长', '替代测试'], answer: 0, explanation: '检查点避免从头执行。' },
      ],
    ),
  },
  {
    id: 8,
    act: 3,
    title: '工具选择、成本与可靠性',
    duration: 17,
    sourceRange: '原文 5.2、5.5、9.2–9.4',
    problem: '同一任务有搜索、数据库、计算器三个工具。Agent 既会选错，也会反复调用贵接口。怎样同时提高准确率和控制成本？',
    outcome: '你会通过工具路由、缓存、验证与预算分配，减少“昂贵但错误”的执行。',
    prediction: { prompt: '计算 2387 × 419 时优先用什么？', choices: predictionChoices('搜索引擎', '计算器工具', '长期记忆'), answer: 'b', feedback: '选择最窄、最确定的工具通常更便宜、更可靠。' },
    formula: '先路由，再执行；先校验，再信任；先复用，再调用',
    lesson: [
      { title: '工具描述决定路由质量', paragraphs: ['名称要具体，描述要写适用与不适用场景。相似工具应给出差异，例如“查实时网页”与“查内部订单库”。'] },
      { title: '成本预算分层', paragraphs: ['先用规则或小模型分类，复杂问题再升级强模型；相同请求使用缓存；并行只用于互不依赖且收益明确的步骤。'] },
      { title: '结果不能盲信', paragraphs: ['校验 schema、范围、时间戳和来源。关键结论可用第二来源或确定性代码复核。工具成功返回不代表业务结果正确。'] },
    ],
    practice: { title: '写一张工具路由表', brief: '为搜索、数据库、计算器列出触发条件、禁止场景、成本和验证方式。', success: '面对实时数据、内部数据和数学计算时都能唯一选出工具。' },
    codexTask: { title: '实现带预算的工具路由器', context: '一个分析 Agent 有搜索、数据库和计算器工具。', goal: '依据任务类型选择工具，并记录费用与缓存命中。', scope: ['规则路由优先', '工具级预算', '内存缓存'], constraints: ['总费用超限立即停止', '未知任务返回澄清', '缓存键包含关键参数'], acceptance: ['三类任务选择正确', '重复请求不重复计费', '超预算返回可读原因'], tests: ['路由表测试', '缓存测试', '预算边界测试', '未知意图测试'] },
    bridge: '单个 Agent 可以优化，但任务越来越复杂时，一个大循环会变得难维护。下一关学习多 Agent。',
    quiz: makeQuiz(
      8,
      [
        { prompt: '查询公司内部订单状态应选？', choices: ['公开搜索', '订单数据库工具', '计算器'], answer: 1, explanation: '内部业务事实来自授权数据库。', critical: true },
        { prompt: '相同报表被十次请求，最直接的成本优化？', choices: ['缓存相同输入的有效结果', '每次换更贵模型', '删除校验'], answer: 0, explanation: '缓存避免重复计算与调用。' },
        { prompt: '搜索结果没有日期，Agent 应？', choices: ['直接用于“最新”结论', '检查时间戳或换来源', '自己补日期'], answer: 1, explanation: '时效性是结果可靠性的一部分。' },
        { prompt: '简单意图分类是否一定用最强模型？', choices: ['是', '否，可用规则/小模型并评测', '只看界面'], answer: 1, explanation: '分层路由能兼顾成本与质量。' },
        { prompt: '两个工具名字都叫 search，如何改善？', choices: ['写清内部/外部用途与边界', '让模型猜', '隐藏参数'], answer: 0, explanation: '差异明确的描述能提高选择准确率。' },
      ],
      [
        { prompt: '工具调用成功后还需要？', choices: ['校验结果是否满足业务条件', '立即删除日志', '默认完全可信'], answer: 0, explanation: '技术成功与业务正确不同。' },
        { prompt: '并行调用适合？', choices: ['互不依赖的步骤', '有严格先后依赖的步骤', '所有情况'], answer: 0, explanation: '有依赖的步骤并行会使用不存在的输入。' },
        { prompt: '缓存键必须包含？', choices: ['影响结果的关键参数', '随机数', '页面颜色'], answer: 0, explanation: '否则不同请求可能误用同一结果。' },
      ],
    ),
  },
  {
    id: 9,
    act: 4,
    title: '什么时候需要多 Agent',
    duration: 16,
    sourceRange: '原文 6.1–6.5',
    problem: '研究、写作、事实核验、发布全塞进一个 Agent 后，提示词越来越长，责任也说不清。拆成多个 Agent 就一定更好吗？',
    outcome: '你会判断多 Agent 的必要性，并设计角色、交接协议和失败归属。',
    prediction: { prompt: '哪种情况最值得拆成多个角色？', choices: predictionChoices('只有一步固定查询', '存在清晰专业分工与可验证交接', '想让架构图更复杂'), answer: 'b', feedback: '拆分要带来边界、并行或专业化收益，否则只会增加协调成本。' },
    formula: '多 Agent 收益 > 通信、状态同步、重复工作与调试成本',
    lesson: [
      { title: '按责任边界拆，不按热闹拆', paragraphs: ['研究员负责收集证据，分析员负责计算，编辑负责组织，审核员负责检查。每个角色都应有明确输入、输出和不做什么。'] },
      { title: '三种常见协作', paragraphs: ['顺序交接适合有依赖的流水线；主管—工人适合动态分配；共享黑板适合多角色围绕同一状态协作。'] },
      { title: '交接是最薄弱的地方', paragraphs: ['交接必须结构化：任务、证据、未决问题、置信度、下一步。仅传一句自然语言摘要容易丢失约束。'] },
    ],
    practice: { title: '拆解内容与数据助手', brief: '决定研究、数据分析、写作、审核是否分角色，并写出每次交接字段。', success: '每个角色有独立验收标准，且不存在两个角色都“最终负责”。' },
    bridge: '决定拆分后，还要选实现方式。下一关比较框架，而不是盲目追新工具。',
    quiz: makeQuiz(
      9,
      [
        { prompt: '一个固定查天气任务要拆 4 个 Agent 吗？', choices: ['通常不需要', '必须', '角色越多越准确'], answer: 0, explanation: '简单任务的协调成本大于收益。', critical: true },
        { prompt: '研究员交给编辑时最重要的内容是？', choices: ['证据、来源、未决问题与置信度', '一句“写得不错”', '自己的头像'], answer: 0, explanation: '结构化交接保留决策依据。' },
        { prompt: '多个独立数据源可同时查询，适合哪种协作？', choices: ['并行分工后汇总', '严格串行', '全部交给同一工具重复查'], answer: 0, explanation: '互不依赖的查询可以并行。' },
        { prompt: '两个角色同时修改同一状态，首先需要？', choices: ['冲突与版本控制', '更多欢迎语', '更长角色名'], answer: 0, explanation: '共享状态必须防止覆盖和竞态。' },
        { prompt: '审核 Agent 发现证据不足，应该？', choices: ['退回带明确缺口', '自己编造来源', '直接发布'], answer: 0, explanation: '审核角色应输出可行动的失败原因。' },
      ],
      [
        { prompt: '多 Agent 最大的新增成本是？', choices: ['协调与状态同步', '页面字体', '键盘输入'], answer: 0, explanation: '角色越多，通信与调试越复杂。' },
        { prompt: '角色边界应包含？', choices: ['输入、输出、权限与验收', '只写人设', '只写名字'], answer: 0, explanation: '可执行边界比角色故事更重要。' },
        { prompt: '主管—工人模式适合？', choices: ['需要动态分解和分派子任务', '完全固定的一步任务', '没有目标的聊天'], answer: 0, explanation: '主管根据进展分派不同工作。' },
      ],
    ),
  },
  {
    id: 10,
    act: 4,
    title: '框架只是实现选择',
    duration: 17,
    sourceRange: '原文 7.1–7.6',
    problem: 'LangChain、AutoGen、CrewAI、Dify 都能做 Agent。新手应该从“最热门”开始，还是从任务形状开始？',
    outcome: '你会按状态复杂度、协作模式、可视化需求与团队能力选框架，也知道何时先用普通代码。',
    prediction: { prompt: '一个可预测的三步流程，最合适的起点是什么？', choices: predictionChoices('先用最小状态机或普通函数', '立即上多 Agent 框架', '同时接入四个框架'), answer: 'a', feedback: '先用最小能表达流程的工具，复杂度出现后再升级。' },
    formula: '先画状态与边，再选择能清楚表达它们的框架',
    lesson: [
      { title: '框架解决的是工程问题', paragraphs: ['它们提供模型调用、工具封装、状态流转、角色协作、可视化或部署能力。框架不会自动给你正确的任务边界、数据和评测。'] },
      { title: '按任务形状选', paragraphs: ['链式调用和丰富集成可考虑 LangChain；显式状态与分支适合图式编排；对话型多角色可考虑 AutoGen；角色流水线适合 CrewAI；低代码原型和运营配置可考虑 Dify。'] },
      { title: '避免框架锁定', paragraphs: ['把业务规则、工具接口和评测数据独立出来。框架只负责编排，这样未来替换模型或框架时不用重写业务核心。'] },
    ],
    practice: { title: '为三个任务选实现', brief: '分别为固定日报、带审批的退款流程、多角色内容生产选择最小实现。', success: '每个选择都能说出不用更复杂方案的理由。' },
    codexTask: { title: '先画图，再让 Codex 搭骨架', context: '需要实现带审批分支的退款流程。', goal: '用显式状态、节点与边搭建可测试骨架。', scope: ['输入校验', '资格查询', '人工审批', '结果输出'], constraints: ['业务规则与框架代码分离', '节点输入输出有类型', '所有分支有终态'], acceptance: ['正常与拒绝路径都可运行', '审批前不执行退款', '状态可序列化'], tests: ['每个节点单测', '两条端到端路径', '未知状态失败测试'] },
    bridge: '框架搭起来只是开始。没有评测和监控，你不知道系统到底有没有变好。',
    quiz: makeQuiz(
      10,
      [
        { prompt: '退款流程有明确分支和审批节点，应优先看什么能力？', choices: ['显式状态与图式编排', '角色故事生成', '图片滤镜'], answer: 0, explanation: '可观察状态和分支是核心需求。', critical: true },
        { prompt: '业务同学需要拖拽配置简单工作流，适合优先评估？', choices: ['低代码平台', '手写汇编', '多 Agent 辩论'], answer: 0, explanation: '可视化配置与部署是关键需求。' },
        { prompt: '框架升级导致 API 变化，怎样降低影响？', choices: ['隔离业务规则与框架适配层', '把业务写进每个节点', '不写测试'], answer: 0, explanation: '边界隔离减少锁定。' },
        { prompt: '三步固定日报流程应该？', choices: ['从普通函数/小状态机开始', '上十个 Agent', '每步换一个框架'], answer: 0, explanation: '最小实现更易理解和验证。' },
        { prompt: '对话式多角色协作更看重？', choices: ['消息路由与角色通信', '数据库主题色', '视频转码'], answer: 0, explanation: '任务形状决定框架能力。' },
      ],
      [
        { prompt: '框架能自动替你解决什么？', choices: ['编排与集成基础设施', '正确业务目标', '真实评测数据'], answer: 0, explanation: '业务定义仍需自己完成。' },
        { prompt: '选框架前最该先做？', choices: ['画状态、分支和工具边界', '看社交媒体热度', '写品牌口号'], answer: 0, explanation: '先理解问题形状。' },
        { prompt: '可移植设计应把什么独立？', choices: ['业务规则、工具接口、评测', '所有内容绑死框架', '只保留 UI'], answer: 0, explanation: '这些是系统长期资产。' },
      ],
    ),
  },
  {
    id: 11,
    act: 4,
    title: '用评测与监控闭环',
    duration: 18,
    sourceRange: '原文 9.4–9.5、意图识别 7.3',
    problem: '改了提示词后，演示案例变好了，但线上投诉变多。没有数据时，“感觉更聪明”毫无意义。怎样证明改动有效？',
    outcome: '你会建立离线评测集、线上指标与可追踪日志，能定位一次失败发生在哪一步。',
    prediction: { prompt: '发布前最先需要什么？', choices: predictionChoices('一组真实且覆盖边界的固定测试任务', '更炫的加载动画', '删除旧日志'), answer: 'a', feedback: '固定评测集让不同版本在同一尺度上比较。' },
    formula: '质量 = 任务成功率 + 安全性 + 成本 + 延迟；每项都要可追踪',
    lesson: [
      { title: '评测从真实失败出发', paragraphs: ['样本应覆盖常见请求、模糊表达、缺参、工具故障、高风险动作和对抗输入。每个样本要有可判定的期望结果。'] },
      { title: '过程与结果都要测', paragraphs: ['最终答案正确不代表过程安全。还要检查工具是否选对、参数是否正确、是否越权、调用次数与延迟是否在预算内。'] },
      { title: '日志是任务时间线', paragraphs: ['为每次运行分配 trace id，记录每一步输入摘要、动作、工具结果、耗时、成本、重试与终态。敏感数据在记录前脱敏。'] },
    ],
    practice: { title: '写 10 条评测样本', brief: '为订单客服写正常、缺参、过期、接口失败、越权等样本和期望行为。', success: '每条都能自动或人工明确判定通过/失败。' },
    bridge: '评测能告诉你系统哪里差。最后一个关键输入层问题是：用户往往不会把需求说得像 API 参数。',
    quiz: makeQuiz(
      11,
      [
        { prompt: '新版本成功率提高，但平均成本翻三倍。能直接发布吗？', choices: ['不能，需看综合目标与预算', '能，只看成功率', '删除成本指标'], answer: 0, explanation: '质量是多目标权衡。', critical: true },
        { prompt: 'Agent 最终答对，但调用了无权限工具。评测应？', choices: ['判通过', '判安全失败', '忽略过程'], answer: 1, explanation: '正确结果不能抵消越权过程。' },
        { prompt: '线上一次失败难复现，最需要？', choices: ['trace id 与步骤日志', '随机换模型', '隐藏错误'], answer: 0, explanation: '可追踪时间线支持定位与复现。' },
        { prompt: '评测集全部是清晰标准问法，会漏掉什么？', choices: ['模糊、缺参和真实表达', '页面响应式', '字体加载'], answer: 0, explanation: '真实用户输入往往不标准。' },
        { prompt: '日志里含用户手机号，应该？', choices: ['脱敏后记录必要部分', '原样永久保存', '公开分享'], answer: 0, explanation: '可观测性不能牺牲隐私。' },
      ],
      [
        { prompt: '离线评测的主要价值是？', choices: ['在固定任务上比较版本', '替代线上监控', '生成宣传数据'], answer: 0, explanation: '固定尺度使改动可比较。' },
        { prompt: 'Agent 评测至少关注？', choices: ['结果、过程、安全、成本、延迟', '只看文风', '只看模型名称'], answer: 0, explanation: '单一准确率不足以评价系统。' },
        { prompt: '一条有效测试样本必须有？', choices: ['明确期望结果或判分规则', '很长的背景', '漂亮截图'], answer: 0, explanation: '没有判定标准就无法比较。' },
      ],
    ),
  },
  {
    id: 12,
    act: 5,
    title: '从用户话语识别真实意图',
    duration: 16,
    sourceRange: '补充：意图识别 1.1–3.3',
    problem: '用户说“我等这个包裹等一周了”，他没有明确说“查询物流”，但一个好客服应该知道下一步。怎样让系统听懂话外之意？',
    outcome: '你会把自然语言转成意图、槽位与置信度，并知道规则、分类模型和大模型各适合什么场景。',
    prediction: { prompt: '这句话最可能对应什么意图？', choices: predictionChoices('查询物流/催单', '修改头像', '申请发票'), answer: 'a', feedback: '意图识别关注用户想完成的动作，而不仅是字面关键词。' },
    formula: '用户话语 → 文本理解 → 意图分类 → 槽位提取 → 置信度 → 动作',
    lesson: [
      { title: '意图是动作，槽位是参数', paragraphs: ['“帮我退昨天买的蓝色耳机”中，意图是退货；日期、商品、颜色是执行所需槽位。分类对了但槽位缺失，仍不能安全执行。'] },
      { title: '三种方法各有位置', paragraphs: ['规则适合少量稳定、关键词明确的场景；传统分类模型适合标签固定且样本充足；大模型适合复杂表达和冷启动，但仍要结构化输出与评测。'] },
      { title: '低置信度不是失败', paragraphs: ['当多个意图接近或关键槽位缺失时，最优动作往往是澄清。把不确定性暴露出来，比武断执行更可靠。'] },
    ],
    practice: { title: '标注 12 句话', brief: '为客服语句标注意图、槽位、缺失字段和建议动作。', success: '至少包含 3 条隐含表达和 3 条需要追问的输入。' },
    bridge: '单一意图容易处理；真实用户常把多个要求塞进一句话。下一关处理多意图、槽位验证与置信度。',
    quiz: makeQuiz(
      12,
      [
        { prompt: '“这个月账单怎么比上月高？”最可能意图是？', choices: ['账单解释/查询', '取消账号', '修改地址'], answer: 0, explanation: '应从用户想解决的问题判断，而非只看单个词。', critical: true },
        { prompt: '识别为“订票”但没有出发地。下一步？', choices: ['追问出发地', '随机选择', '直接付款'], answer: 0, explanation: '关键槽位缺失时应澄清。' },
        { prompt: '只有 8 个固定命令且表达高度稳定，优先？', choices: ['简单规则', '最强多模态模型', '多 Agent'], answer: 0, explanation: '规则便宜、可解释且足够。' },
        { prompt: '大量已标注客服意图，标签稳定，适合？', choices: ['训练分类器并持续评测', '不做分类', '只写正则'], answer: 0, explanation: '固定标签和充足样本适合监督分类。' },
        { prompt: '两个意图置信度接近且动作风险高，应？', choices: ['请求用户确认', '选第一个直接执行', '同时执行两个'], answer: 0, explanation: '不确定且高风险时必须澄清。' },
      ],
      [
        { prompt: '槽位在意图系统中代表？', choices: ['执行动作所需参数', '页面位置', '模型大小'], answer: 0, explanation: '槽位把对象、时间、金额等信息结构化。' },
        { prompt: '意图识别关注的是？', choices: ['用户想完成的动作', '句子长度', '标点数量'], answer: 0, explanation: '真实目标比字面形式重要。' },
        { prompt: '置信度的主要用途是？', choices: ['决定执行、澄清或升级', '改变主题色', '增加回复长度'], answer: 0, explanation: '置信度帮助控制风险。' },
      ],
    ),
  },
  {
    id: 13,
    act: 5,
    title: '多意图、槽位与置信度',
    duration: 17,
    sourceRange: '补充：意图识别 4.1–7.3',
    problem: '用户说“查下北京明天天气，然后订一张周五去上海的票”。如果只取一个意图，任务会漏一半；如果盲目拆句，又可能破坏语义。',
    outcome: '你会设计多意图序列、槽位验证、置信度校准和可评测的识别结果。',
    prediction: { prompt: '这句话应该输出什么结构？', choices: predictionChoices('两个有顺序的意图及各自槽位', '只保留最后一个意图', '整句话作为一个工具名'), answer: 'a', feedback: '多意图结果要保留顺序、依赖和各自参数。' },
    formula: '多意图 = 拆分候选 + 分别识别 + 依赖排序 + 槽位验证 + 联合执行',
    lesson: [
      { title: '先识别边界，再分类', paragraphs: ['“然后、同时、还要”是线索但不是完整答案。拆分后要检查代词和共享槽位，例如“查北京天气并订那里的酒店”共享地点。'] },
      { title: '槽位验证决定能否执行', paragraphs: ['每个意图有必填、可选、默认与格式约束。验证失败时输出缺失槽位，不应直接进入业务工具。'] },
      { title: '校准置信度', paragraphs: ['0.9 不应只是模型随口给的数字。用验证集观察不同分数下的真实正确率，并为低风险与高风险动作设置不同阈值。'] },
    ],
    codeLens: { title: '识别结果要能驱动流程', code: `type IntentResult = {\n  intents: Array<{\n    name: IntentName\n    slots: Record<string, string>\n    confidence: number\n    missing: string[]\n  }>\n}`, watch: ['intents 是有序数组', 'missing 决定是否追问', 'confidence 需要经过评测校准'] },
    practice: { title: '设计多意图识别结果', brief: '为“查订单并把收货地址改到公司”写出两个意图、槽位、依赖和确认点。', success: '先确认订单，再在修改地址前检查是否允许变更并请求确认。' },
    bridge: '现在输入、规划、工具和评测都齐了。下一关把它们装进一个真实产品方案。',
    quiz: makeQuiz(
      13,
      [
        { prompt: '“查订单并取消它”中的两个意图有什么依赖？', choices: ['先查到订单，再取消', '完全独立', '先取消再查'], answer: 0, explanation: '后一个动作依赖前一个得到的订单对象。', critical: true },
        { prompt: '“订北京酒店和那里的景点票”拆分时要保留？', choices: ['共享地点北京', '只保留第二句', '删除代词关系'], answer: 0, explanation: '跨意图共享槽位不能丢失。' },
        { prompt: '退款意图置信度 0.62，阈值 0.85。应？', choices: ['澄清或转人工', '直接退款', '提高显示的数字'], answer: 0, explanation: '高风险动作未达阈值不能执行。' },
        { prompt: '意图正确，但金额格式为“很多”。系统应？', choices: ['槽位验证失败并追问', '随便填金额', '跳过金额'], answer: 0, explanation: '格式不合法等同关键参数缺失。' },
        { prompt: '模型给所有结果都报 0.99，但真实准确率只有 70%。说明？', choices: ['置信度未校准', '系统完美', '需要更亮颜色'], answer: 0, explanation: '分数与真实正确率不匹配。' },
      ],
      [
        { prompt: '多意图输出为什么应保留顺序？', choices: ['后续动作可能依赖前一步结果', '为了文案更长', '没有原因'], answer: 0, explanation: '执行依赖必须可表达。' },
        { prompt: 'missing 字段最直接驱动？', choices: ['澄清问题', '立即执行', '删除会话'], answer: 0, explanation: '缺失关键槽位时应追问。' },
        { prompt: '不同风险动作是否应共用同一置信阈值？', choices: ['不一定，高风险通常更高', '必须完全相同', '不需要阈值'], answer: 0, explanation: '阈值要与错误代价匹配。' },
      ],
    ),
  },
  {
    id: 14,
    act: 5,
    title: '设计内容与数据助手',
    duration: 22,
    sourceRange: '原文 8.1–8.3、9.1–9.5',
    problem: '你要做一个能读取表格、发现趋势、生成内容草稿并给出来源的助手。怎样把它限定成一个能真正完成的第一版？',
    outcome: '你会完成产品边界、状态图、工具合同、风险点和评测集，形成可交给 Codex 的工程任务。',
    prediction: { prompt: '第一版最应该砍掉什么？', choices: predictionChoices('一个明确输入到一个可验收输出的主流程', '自动对外发布与无限数据源', '必要的错误提示'), answer: 'b', feedback: '第一版应先证明核心闭环；自动发布和无限接入会迅速放大风险与复杂度。' },
    formula: 'CSV/表格 → 校验 → 分析 → 证据 → 草稿 → 人工确认 → 导出',
    lesson: [
      { title: '把第一版写成一条主路径', paragraphs: ['输入限定为 CSV 或粘贴表格；输出限定为趋势摘要、三条证据和一份内容草稿。任何数字都要能回到源数据。'] },
      { title: '工具与状态', paragraphs: ['工具包括解析表格、计算指标、生成图表数据、写草稿和导出。状态保存字段映射、分析结果、证据引用、草稿版本和审批状态。'] },
      { title: '风险与确认点', paragraphs: ['数据解析失败要停止；数字结论必须代码复核；外发前必须人工确认；敏感字段默认不进入模型；无法支持的结论要明确标注。'] },
    ],
    practice: { title: '写一页产品规格', brief: '完成用户输入、核心流程、工具、状态、失败分支、确认点和 10 条评测样本。', success: '另一位开发者不需要口头补充就能搭出 mock 版本。' },
    codexTask: { title: '搭建内容与数据助手 Mock 版', context: '个人本地使用，先验证分析到草稿的闭环。', goal: '读取示例 CSV，计算趋势，生成带证据引用的草稿并允许导出。', scope: ['CSV 上传与字段映射', '确定性指标计算', 'Mock 文案生成', '人工确认与 Markdown 导出'], constraints: ['不接真实外部 API', '原始数据只在本地', '每个数字附行列来源', '失败不生成结论'], acceptance: ['示例数据完整跑通', '缺字段给出可操作错误', '草稿可追溯到证据', '刷新后保留未完成状态'], tests: ['CSV 正常/空文件/坏格式', '指标计算单测', '证据引用测试', '未确认禁止导出测试'] },
    bridge: '设计完成后，最后一关不是“再学一个概念”，而是用验收和迭代把它做成能用的东西。',
    quiz: makeQuiz(
      14,
      [
        { prompt: '第一版是否应自动发布到所有平台？', choices: ['不应，先保留人工确认', '应，越自动越好', '与风险无关'], answer: 0, explanation: '外发是高影响动作，第一版应先验证闭环。', critical: true },
        { prompt: '草稿写“转化率增长 18%”，系统必须保存？', choices: ['计算口径与源数据引用', '只保存句子', '模型温度'], answer: 0, explanation: '数字结论必须可追溯。' },
        { prompt: 'CSV 缺少日期列，正确行为是？', choices: ['说明缺失并要求映射/补充', '猜日期', '生成趋势结论'], answer: 0, explanation: '关键字段缺失时不能继续分析。' },
        { prompt: '敏感客户手机号是否默认发给模型？', choices: ['不，应先移除或脱敏', '是', '只要日志关闭就行'], answer: 0, explanation: '数据最小化从输入层开始。' },
        { prompt: '哪个输出最容易验收？', choices: ['一份带三条证据引用的趋势草稿', '做一个万能助手', '让内容更有感觉'], answer: 0, explanation: '具体输出才有明确完成标准。' },
      ],
      [
        { prompt: '第一版主流程最好是？', choices: ['单一输入到可验收输出的闭环', '覆盖所有场景', '没有边界'], answer: 0, explanation: '窄闭环更容易验证价值。' },
        { prompt: '指标计算应优先由什么完成？', choices: ['确定性代码', '模型自由猜测', '随机抽样'], answer: 0, explanation: '可复现计算交给代码更可靠。' },
        { prompt: '产品规格应包含？', choices: ['输入、流程、状态、风险、验收、测试', '只有页面颜色', '只有模型名称'], answer: 0, explanation: '这些信息足以指导实现与验证。' },
      ],
    ),
  },
  {
    id: 15,
    act: 5,
    title: '验收、复盘与第一次迭代',
    duration: 20,
    sourceRange: '原文 9.1–10.1、意图识别 7.1–7.3',
    problem: 'Mock 版终于跑通，但你不知道它是否真的可靠，也不知道下一步该接 API、加功能还是先修失败样本。',
    outcome: '你会用验收矩阵决定是否发布，并把真实失败转成下一轮需求，而不是凭兴奋继续堆功能。',
    prediction: { prompt: '第一轮迭代优先看什么？', choices: predictionChoices('失败频率 × 影响程度最高的问题', '最酷的新框架', '动画是否更多'), answer: 'a', feedback: '优先修复高频、高影响且可复现的问题，收益比继续扩功能更大。' },
    formula: '运行 → 观察 → 归因 → 修一处 → 回归评测 → 再发布',
    lesson: [
      { title: '用验收矩阵做发布判断', paragraphs: ['列出主路径、边界输入、工具故障、安全动作、成本与延迟。每项有阈值和证据，不能只靠“我试了几次没问题”。'] },
      { title: '失败先分类再修', paragraphs: ['区分意图错误、规划错误、工具错误、数据错误、控制错误与呈现错误。每次只改变一个主要因素，才能知道改动是否有效。'] },
      { title: '真实 API 最后接', paragraphs: ['Mock 流程稳定后，单独创建 Codex 实现任务接入 API；密钥放在 .env 和服务端边界，不写进前端、日志或导出文件。'] },
    ],
    codeLens: { title: '验收条件要能运行', code: `expect(result.status).toBe('needs_confirmation')\nexpect(result.evidence).toHaveLength(3)\nexpect(toolCalls.publish).toHaveLength(0)`, watch: ['测试检查状态而非文风', '证据数量是明确合同', '未确认时发布调用必须为零'] },
    practice: { title: '完成一次发布评审', brief: '跑完评测集，按失败类型分组，选一个最高优先级问题修复并回归。', success: '修复后旧样本不回退，新失败样本已加入固定评测集。' },
    codexTask: { title: '接入真实 API 的独立任务', context: 'Mock 版已通过验收，需要把文案生成替换为真实模型 API。', goal: '在服务端边界接入 API，并保持现有输入输出合同。', scope: ['服务端代理', '环境变量读取', '超时与有限重试', '费用与 trace 日志'], constraints: ['API Key 只放 .env', '前端和 localStorage 不出现密钥', '日志不记录完整敏感输入', 'Mock 模式仍可用'], acceptance: ['无密钥时给出明确配置错误', '成功路径与 Mock 合同一致', '超时可恢复', '费用可见'], tests: ['密钥缺失', '成功响应', '429 退避', '超时停止', '响应 schema 错误'] },
    bridge: '你已经完成 Agent 手册主线。之后新增 RAG、LangChain、LangGraph 等文档时，继续沿用同一套“问题—概念—实践—测验—复习”路径。',
    quiz: makeQuiz(
      15,
      [
        { prompt: '真实 API Key 应放在哪里？', choices: ['服务端环境变量 .env', '前端源码', 'localStorage'], answer: 0, explanation: '密钥必须留在受控的服务端边界。', critical: true },
        { prompt: '修复一个失败后最重要的动作是？', choices: ['加入回归评测并重跑旧样本', '删除失败记录', '立即加新功能'], answer: 0, explanation: '回归防止同类问题再次出现。' },
        { prompt: '同一轮同时改模型、提示词和工具，结果变好。能知道原因吗？', choices: ['不能，应控制变量', '能，一定是模型', '能，一定是工具'], answer: 0, explanation: '一次改多个因素无法归因。' },
        { prompt: '一个低频但会误发公开内容的问题优先级？', choices: ['高，因为影响严重', '低，只看频率', '不用修'], answer: 0, explanation: '优先级取决于频率与影响。' },
        { prompt: '真实 API 暂时不可用，产品应？', choices: ['保留 Mock/降级路径并清楚说明', '白屏', '伪造响应'], answer: 0, explanation: '可控降级比隐性失败可靠。' },
      ],
      [
        { prompt: '发布判断应基于？', choices: ['带阈值和证据的验收矩阵', '个人感觉', '模型热度'], answer: 0, explanation: '明确标准才能复现决策。' },
        { prompt: '失败归因的价值是？', choices: ['把修复落到正确层', '让报告更长', '避免测试'], answer: 0, explanation: '不同类型问题需要不同修复。' },
        { prompt: '迭代的正确节奏是？', choices: ['观察、归因、单点修改、回归', '一直加功能', '每次全部重写'], answer: 0, explanation: '小步可验证迭代能积累可靠性。' },
      ],
    ),
  },
]

export const getStage = (stageId: number) => stages.find((stage) => stage.id === stageId) ?? stages[0]
